/*
    Copyright (C) 2012  Spatial Transcriptomics AB,
    read LICENSE for licensing terms.
    Contact : Jose Fernandez Navarro <jose.fernandez.navarro@scilifelab.se>

*/

#ifndef SERVERERROR_H
#define SERVERERROR_H

#include "Error.h"

//Error class to parse errors generated by the Server (API) or the OAuth2 server
class ServerError : public Error
{
    Q_OBJECT

public:

    ServerError(const QString& serverErrorName,
                const QString& serverErrorDescription, QObject *parent = 0);
    virtual ~ServerError();

private:

    void init(const QString &serverErrorName = QString(),
              const QString &serverErrorDescription = QString());

};

#endif // SERVERERROR_H //
